# Kitty — ~/.config/kitty/kitty.conf

# Цвета генерируются theme.sh
include colors.conf
# Стиль (прозрачность) переключается style.sh
include style.conf

# Шрифт
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
font_size        12.0

# Окно
window_padding_width 12
hide_window_decorations yes
confirm_os_window_close 0
remote_control_password ""
allow_remote_control socket-only
listen_on unix:/tmp/kitty

# Курсор
cursor_shape beam
cursor_blink_interval 0.5

# Скроллбэк
scrollback_lines 10000

# Вкладки
tab_bar_style powerline
tab_powerline_style slanted

# Звук
enable_audio_bell no

# Хоткеи
map ctrl+shift+t new_tab
map ctrl+shift+w close_tab
map ctrl+shift+right next_tab
map ctrl+shift+left previous_tab
map ctrl+shift+enter new_window
map ctrl+shift+plus change_font_size all +1.0
map ctrl+shift+minus change_font_size all -1.0
