# hypridle — ~/.config/hypr/hypridle.conf

general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Приглушить яркость через 5 минут
listener {
    timeout = 300
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

# Заблокировать через 10 минут
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

# Выключить экран через 15 минут
listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Сон через 30 минут
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
