# hyprpaper — ~/.config/hypr/hyprpaper.conf
# Положи обои в ~/Pictures/wallpapers/wall.png

preload = ~/Pictures/wallpapers/wall.png
wallpaper = , ~/Pictures/wallpapers/wall.png
splash = false
ipc = on
