# Сгенерировано theme.sh
[global]
    frame_color = "#7aa2f7"

[urgency_low]
    background = "#090c13"
    foreground = "#b5cbfa"

[urgency_normal]
    background = "#090c13"
    foreground = "#eff3fe"

[urgency_critical]
    background = "#090c13"
    foreground = "#f38ba8"
    frame_color = "#f38ba8"
